version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: intercom_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/intercom_db
      
volumes:
  postgres_data: 